language: node_js
node_js:
  - "10"
before_install:
  - npm i node-fetch
cache:
  directories:
    - "node_modules"
script:
    - node index.js
deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
          - daily_new_downloads.json
          - weekly_new_downloads.json
          - monthly_new_downloads.json
          - yearly_new_downloads.json
          - daily_updates.json
          - weekly_updates.json
          - monthly_updates.json
          - yearly_updates.json
        overwrite: true
        skip_cleanup: true
