language: node_js
node_js:
  - "12"
before_install:
  - npm i node-fetch
cache:
  directories:
    - "node_modules"
script:
    - node index.js; node index-newinst-updates.js
before_deploy:
      # Set up git user name and tag this commit
    - git config --local user.name $GIT_USER_NAME
    - git config --local user.email $GIT_USER_EMAIL
    - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"    
deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
          - daily.json
          - daily_new_downloads.json
          - daily_updates.json
          - weekly.json
          - weekly_new_downloads.json
          - weekly_updates.json
          - monthly.json
          - monthly_new_downloads.json
          - monthly_updates.json
          - yearly.json
          - yearly_new_downloads.json
          - yearly_updates.json
        overwrite: true
        skip_cleanup: true
