name: Fetch & merge the stats 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo npm i -g node-fetch & node index.js
    - run: hub release create -m 'Regular nightly build' -a daily.json -a weekly.json -a monthly.json -a yearly.json nightly
      env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - run: node index-newinst-updates.js - under construction
